CREATE PROCEDURE [dbo].[SetProduceValues]
AS

INSERT INTO Produce
VALUES ('Carrots',3.00)
INSERT INTO PRODUCE
VALUES('Potatoes',2.00)
INSERT INTO PRODUCE
VALUES('Corn',1.50)
INSERT INTO PRODUCE
VALUES('Apple',2.00)
INSERT INTO PRODUCE
VALUES('Pineapple',3.00)
INSERT INTO PRODUCE
VALUES('Avocado',2.00)
INSERT INTO PRODUCE
VALUES('Artichoke',0.61)
INSERT INTO PRODUCE
VALUES('Arugula',1.01)
INSERT INTO PRODUCE
VALUES('Basil',1.78)
INSERT INTO PRODUCE
VALUES('Bananas',0.86)
INSERT INTO PRODUCE
VALUES('Bok Choy',2.04)
INSERT INTO PRODUCE
VALUES('Celery',0.86)
INSERT INTO PRODUCE
VALUES('Coconut',1.06)
INSERT INTO PRODUCE
VALUES('Cucumber',1.93)
INSERT INTO PRODUCE
VALUES('Eggplant',2.48)
INSERT INTO PRODUCE
VALUES('Daikon',1.12)
INSERT INTO PRODUCE
VALUES('Garlic',3.47)
INSERT INTO PRODUCE
VALUES('Grapefruit',1.09)
INSERT INTO PRODUCE
VALUES('Kiwi',0.28)
INSERT INTO PRODUCE
VALUES('Lemons',1.15)
INSERT INTO PRODUCE
VALUES('Squash',2.53)
INSERT INTO PRODUCE
VALUES('Kale',15.36)
INSERT INTO PRODUCE
VALUES('Strawberries',2.54)
INSERT INTO PRODUCE
VALUES('Mango',1.23)